/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "mapping_person" CASCADE;

CREATE TABLE "mapping_person" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "first" TEXT NOT NULL,
  "last" TEXT NOT NULL,
  "born" DATE NOT NULL,
  "married" VARCHAR(5) NOT NULL);

