/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "section_person_nicknames" CASCADE;

DROP TABLE IF EXISTS "section_person" CASCADE;

CREATE TABLE "section_person" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "first" TEXT NOT NULL,
  "last" TEXT NOT NULL,
  "bio" TEXT NOT NULL);

CREATE TABLE "section_person_nicknames" (
  "object_id" BIGINT NOT NULL,
  "index" BIGINT NOT NULL,
  "value" TEXT NOT NULL,
  CONSTRAINT "object_id_fk"
    FOREIGN KEY ("object_id")
    REFERENCES "section_person" ("id")
    ON DELETE CASCADE);

CREATE INDEX "section_person_nicknames_object_id_i"
  ON "section_person_nicknames" ("object_id");

CREATE INDEX "section_person_nicknames_index_i"
  ON "section_person_nicknames" ("index");

