string script;
	
	script =	"CREATE TABLE `GraphClass`"
				"("
				"`graphClassName`	VARCHAR(" + std::to_string((_ULonglong)constants::SIZE_MAX_GRAPH_NAME) + ") NOT NULL UNIQUE PRIMARY KEY,"
					"`directGraph`		BOOLEAN DEFAULT '0',"
					"`acyclicGraph`		BOOLEAN DEFAULT '0'"
				");"
	
				"CREATE TABLE `ObjectClass`"
				"("
					"`objectClassName`	VARCHAR("+ std::to_string((_ULonglong)constants::SIZE_MAX_CLASS_NAME)+") NOT NULL UNIQUE PRIMARY KEY"
				");"

				"CREATE TABLE `Graphs`"
				"("
					"`idGraph` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,"
					"`graphClass`	VARCHAR("+ std::to_string((_ULonglong)constants::SIZE_MAX_GRAPH_NAME)+") NOT NULL,"
					"`objectClass`	VARCHAR("+ std::to_string((_ULonglong)constants::SIZE_MAX_CLASS_NAME)+") NOT NULL,"
					"`objectName`	VARCHAR("+ std::to_string((_ULonglong)constants::SIZE_MAX_OBJ_NAME)+") NOT NULL UNIQUE,"
					"`viewNumber`	INTEGER DEFAULT '1' NOT NULL,"
					"FOREIGN KEY(`graphClass`) REFERENCES `GraphClass`(`graphClassName`) ON DELETE CASCADE,"
					"FOREIGN KEY(`objectClass`) REFERENCES `ObjectClass`(`objectClassName`) ON DELETE CASCADE"
				");"

				"CREATE INDEX `index_Graphs_objectName` ON `Graphs`(`objectName`);"
				"CREATE INDEX `index_Graphs_objectClass` ON `Graphs`(`objectClass`);"
				"CREATE INDEX `index_Graphs_graphClass` ON `Graphs`(`graphClass`);"

				"CREATE TABLE `Nodes`"
				"("
					"`idNode`		INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,"
					"`index`		INTEGER DEFAULT '1' NOT NULL,"
					"`level`		INTEGER DEFAULT '1' NOT NULL,"
					"`mass`			INTEGER DEFAULT '1' NOT NULL,"
					"`type`			INTEGER DEFAULT '1' NOT NULL,"
					"`pointCount`	INTEGER DEFAULT '1' NOT NULL,"
					"`label`		INTEGER DEFAULT '1' NOT NULL,"
					"`refGraph`		INTEGER NOT NULL,"
					"FOREIGN KEY(`refGraph`) REFERENCES `Graphs`(`idGraph`) ON DELETE CASCADE"
				");"

				"CREATE INDEX `index_Node_refGraph` ON `Nodes`(`refGraph`);"

				"CREATE TABLE `Points`"
				"("
					"`idPoint`		INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,"
					"`xCoord`		REAL DEFAULT '1' NOT NULL,"
					"`yCoord`		REAL DEFAULT '1' NOT NULL,"
					"`radius`		REAL DEFAULT '1' NOT NULL,"
					"`refNode`		INTEGER NOT NULL,"
					"`refGraph`		INTEGER NOT NULL,"
					"FOREIGN KEY(`refNode`) REFERENCES `Nodes`(`idNode`) ON DELETE CASCADE,"
					"FOREIGN KEY(`refGraph`) REFERENCES `Graphs`(`idGraph`) ON DELETE CASCADE"
				");"

				"CREATE INDEX `index_Point_refNode` ON `Points`(`refNode`);"
				"CREATE INDEX `index_Point_refGraph` ON `Points`(`refGraph`);"
				"CREATE INDEX `index_Point_region2D` ON `Points` (`xCoord` ASC, `yCoord` ASC);"

				"CREATE TABLE `Edges`"
				"("
					"`idEdge`		INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,"
					"`source`		INTEGER NOT NULL,"
					"`target`		INTEGER NOT NULL,"
					"`weight`		INTEGER DEFAULT '1' NOT NULL,"
					"`refGraph`		INTEGER NOT NULL,"
					"FOREIGN KEY(`source`) REFERENCES `Nodes`(`idNode`) ON DELETE CASCADE,"
					"FOREIGN KEY(`target`) REFERENCES `Nodes`(`idNode`) ON DELETE CASCADE,"
					"FOREIGN KEY(`refGraph`) REFERENCES `Graphs`(`idGraph`) ON DELETE CASCADE"
				");"

				"CREATE INDEX `index_Edges_source` ON `Edges`(`source`);"
				"CREATE INDEX `index_Edges_target` ON `Edges`(`target`);"
				"CREATE INDEX `index_Edges_refGraph` ON `Edges`(`refGraph`);"
	
				"INSERT INTO `GraphClass` ( `graphClassName` ) VALUES ( 'ShockGraph' );";
