/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "GraphClass" CASCADE;

CREATE TABLE "GraphClass" (
  "graphClassName" TEXT NOT NULL PRIMARY KEY,
  "directGraph" BOOLEAN NOT NULL,
  "acyclicGraph" BOOLEAN NOT NULL);

