/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "Graph" CASCADE;

CREATE TABLE "Graph" (
  "idGraph" BIGINT NOT NULL PRIMARY KEY,
  "graphClass" TEXT NOT NULL,
  "objectClass" TEXT NOT NULL,
  "objectName" TEXT NOT NULL,
  "viewNumber" INTEGER NOT NULL);

ALTER TABLE "Graph"
  ADD CONSTRAINT "graphClass_fk"
    FOREIGN KEY ("graphClass")
    REFERENCES "GraphClass" ("graphClassName")
    ON DELETE CASCADE
    INITIALLY DEFERRED,
  ADD CONSTRAINT "objectClass_fk"
    FOREIGN KEY ("objectClass")
    REFERENCES "ObjectClass" ("objectClassName")
    ON DELETE CASCADE
    INITIALLY DEFERRED;

/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "GraphClass" CASCADE;

CREATE TABLE "GraphClass" (
  "graphClassName" TEXT NOT NULL PRIMARY KEY,
  "directGraph" BOOLEAN NOT NULL,
  "acyclicGraph" BOOLEAN NOT NULL);

/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "ObjectClass" CASCADE;

CREATE TABLE "ObjectClass" (
  "objectClassName" TEXT NOT NULL PRIMARY KEY);

