/*
 * HnSRTreeNode.cc
 *
 * DO NOT EDIT THIS FILE!
 *
 * This file is automatically generated by obj2ptr.
 * 2002/09/13 16:15:03
 */

#include "HnSRTree/HnSRTreeNode.hh"
#include "HnSRTree/HnSRTreeNodeObj.hh"

/*
 * HnSRTreeNode
 */

const HnSRTreeNode HnSRTreeNode::null;

HnSRTreeNode
new_HnSRTreeNode(const HnSRTreeInfo &info, long offset)
{
    HnSRTreeNodeObj *_obj;

    _obj = new HnSRTreeNodeObj(info, offset);

    if ( _obj->hasConstructorFailed() ) {
        delete _obj;
        return (HnSRTreeNodeObj *)NULL;
    }

    return _obj;
}

HnSRTreeNode
new_HnSRTreeNode(const HnSRTreeInfo &info, const HnSRTreeBlock &block)
{
    HnSRTreeNodeObj *_obj;

    _obj = new HnSRTreeNodeObj(info, block);

    if ( _obj->hasConstructorFailed() ) {
        delete _obj;
        return (HnSRTreeNodeObj *)NULL;
    }

    return _obj;
}

#define HnClass HnSRTreeNode
#include "HnSRTree/HnClassArray.cpp"

