/*
 * HnSRTreeCluster.cc
 *
 * DO NOT EDIT THIS FILE!
 *
 * This file is automatically generated by obj2ptr.
 * 2002/09/13 14:07:14
 */

#include "HnSRTree/HnSRTreeCluster.hh"
#include "HnSRTree/HnSRTreeClusterObj.hh"

/*
 * HnSRTreeCluster
 */

const HnSRTreeCluster HnSRTreeCluster::null;

HnSRTreeCluster
new_HnSRTreeCluster(const HnPoint &centroid, int weight, const HnSphere &sphere, const HnRect &rect)
{
    HnSRTreeClusterObj *_obj;

    _obj = new HnSRTreeClusterObj(centroid, weight, sphere, rect);

    if ( _obj->hasConstructorFailed() ) {
        delete _obj;
        return (HnSRTreeClusterObj *)NULL;
    }

    return _obj;
}

#define HnClass HnSRTreeCluster
#include "HnSRTree/HnClassArray.cpp"

