/*
 * HnSRTreeReinsert.cc
 *
 * DO NOT EDIT THIS FILE!
 *
 * This file is automatically generated by obj2ptr.
 * 2002/09/13 16:15:03
 */

#include "HnSRTree/HnSRTreeReinsert.hh"
#include "HnSRTree/HnSRTreeReinsertObj.hh"

/*
 * HnSRTreeReinsert
 */

const HnSRTreeReinsert HnSRTreeReinsert::null;

HnSRTreeReinsert
new_HnSRTreeReinsert(const HnPoint &point, const HnDataItem &dataItem)
{
    HnSRTreeReinsertObj *_obj;

    _obj = new HnSRTreeReinsertObj(point, dataItem);

    if ( _obj->hasConstructorFailed() ) {
        delete _obj;
        return (HnSRTreeReinsertObj *)NULL;
    }

    return _obj;
}

HnSRTreeReinsert
new_HnSRTreeReinsert(long offset, int level)
{
    HnSRTreeReinsertObj *_obj;

    _obj = new HnSRTreeReinsertObj(offset, level);

    if ( _obj->hasConstructorFailed() ) {
        delete _obj;
        return (HnSRTreeReinsertObj *)NULL;
    }

    return _obj;
}

#define HnClass HnSRTreeReinsert
#include "HnSRTree/HnClassArray.cpp"

