// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef EDGE_ODB_HXX
#define EDGE_ODB_HXX

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "Edge.h"

#include "Graph-odb.hxx"
#include "GraphClass-odb.hxx"
#include "Node-odb.hxx"
#include "ObjectClass-odb.hxx"
#include "Point-odb.hxx"

#include <memory>
#include <cstddef>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/prepared-query.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // Edge
  //
  template <>
  struct class_traits< ::Edge >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::Edge >
  {
    public:
    typedef ::Edge object_type;
    typedef ::Edge* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/pgsql/version.hxx>
#include <odb/pgsql/forward.hxx>
#include <odb/pgsql/binding.hxx>
#include <odb/pgsql/pgsql-types.hxx>
#include <odb/pgsql/query.hxx>

namespace odb
{
  // Edge
  //
  template <typename A>
  struct pointer_query_columns< ::Edge, id_pgsql, A >
  {
    // idEdge
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    idEdge_type_;

    static const idEdge_type_ idEdge;

    // source
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    source_type_;

    static const source_type_ source;

    // target
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    target_type_;

    static const target_type_ target;

    // refGraph
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    refGraph_type_;

    static const refGraph_type_ refGraph;

    // weight
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        unsigned int,
        pgsql::id_integer >::query_type,
      pgsql::id_integer >
    weight_type_;

    static const weight_type_ weight;
  };

  template <typename A>
  const typename pointer_query_columns< ::Edge, id_pgsql, A >::idEdge_type_
  pointer_query_columns< ::Edge, id_pgsql, A >::
  idEdge (A::table_name, "\"idEdge\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::Edge, id_pgsql, A >::source_type_
  pointer_query_columns< ::Edge, id_pgsql, A >::
  source (A::table_name, "\"source\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::Edge, id_pgsql, A >::target_type_
  pointer_query_columns< ::Edge, id_pgsql, A >::
  target (A::table_name, "\"target\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::Edge, id_pgsql, A >::refGraph_type_
  pointer_query_columns< ::Edge, id_pgsql, A >::
  refGraph (A::table_name, "\"refGraph\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::Edge, id_pgsql, A >::weight_type_
  pointer_query_columns< ::Edge, id_pgsql, A >::
  weight (A::table_name, "\"weight\"", 0);

  template <>
  class access::object_traits_impl< ::Edge, id_pgsql >:
    public access::object_traits< ::Edge >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // idEdge
      //
      long long idEdge_value;
      bool idEdge_null;

      // source
      //
      long long source_value;
      bool source_null;

      // target
      //
      long long target_value;
      bool target_null;

      // refGraph
      //
      long long refGraph_value;
      bool refGraph_null;

      // weight
      //
      int weight_value;
      bool weight_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    struct source_tag;
    struct target_tag;
    struct refGraph_tag;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static void
    bind (pgsql::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          pgsql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef pgsql::object_statements<object_type> statements_type;

    typedef pgsql::query_base query_base_type;

    static const std::size_t column_count = 5UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static odb::details::shared_ptr<prepared_query_impl>
    prepare_query (connection&, const char*, const query_base_type&);

    static odb::details::shared_ptr<result_impl>
    execute_query (prepared_query_impl&);

    static const char persist_statement_name[];
    static const char find_statement_name[];
    static const char update_statement_name[];
    static const char erase_statement_name[];
    static const char query_statement_name[];
    static const char erase_query_statement_name[];

    static const unsigned int persist_statement_types[];
    static const unsigned int find_statement_types[];
    static const unsigned int update_statement_types[];

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::Edge, id_common >:
    public access::object_traits_impl< ::Edge, id_pgsql >
  {
  };

  // Edge
  //
  template <>
  struct alias_traits<
    ::Node,
    id_pgsql,
    access::object_traits_impl< ::Edge, id_pgsql >::source_tag>
  {
    static const char table_name[];
  };

  template <>
  struct alias_traits<
    ::Node,
    id_pgsql,
    access::object_traits_impl< ::Edge, id_pgsql >::target_tag>
  {
    static const char table_name[];
  };

  template <>
  struct alias_traits<
    ::Graph,
    id_pgsql,
    access::object_traits_impl< ::Edge, id_pgsql >::refGraph_tag>
  {
    static const char table_name[];
  };

  template <>
  struct query_columns_base< ::Edge, id_pgsql >
  {
    // source
    //
    typedef
    odb::alias_traits<
      ::Node,
      id_pgsql,
      access::object_traits_impl< ::Edge, id_pgsql >::source_tag>
    source_alias_;

    // target
    //
    typedef
    odb::alias_traits<
      ::Node,
      id_pgsql,
      access::object_traits_impl< ::Edge, id_pgsql >::target_tag>
    target_alias_;

    // refGraph
    //
    typedef
    odb::alias_traits<
      ::Graph,
      id_pgsql,
      access::object_traits_impl< ::Edge, id_pgsql >::refGraph_tag>
    refGraph_alias_;
  };

  template <typename A>
  struct query_columns< ::Edge, id_pgsql, A >:
    query_columns_base< ::Edge, id_pgsql >
  {
    // idEdge
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    idEdge_type_;

    static const idEdge_type_ idEdge;

    // source
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    source_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::Node,
        id_pgsql,
        source_alias_ > >
    source_pointer_type_;

    struct source_type_: source_pointer_type_, source_column_type_
    {
      source_type_ (const char* t, const char* c, const char* conv)
        : source_column_type_ (t, c, conv)
      {
      }
    };

    static const source_type_ source;

    // target
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    target_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::Node,
        id_pgsql,
        target_alias_ > >
    target_pointer_type_;

    struct target_type_: target_pointer_type_, target_column_type_
    {
      target_type_ (const char* t, const char* c, const char* conv)
        : target_column_type_ (t, c, conv)
      {
      }
    };

    static const target_type_ target;

    // refGraph
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    refGraph_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::Graph,
        id_pgsql,
        refGraph_alias_ > >
    refGraph_pointer_type_;

    struct refGraph_type_: refGraph_pointer_type_, refGraph_column_type_
    {
      refGraph_type_ (const char* t, const char* c, const char* conv)
        : refGraph_column_type_ (t, c, conv)
      {
      }
    };

    static const refGraph_type_ refGraph;

    // weight
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        unsigned int,
        pgsql::id_integer >::query_type,
      pgsql::id_integer >
    weight_type_;

    static const weight_type_ weight;
  };

  template <typename A>
  const typename query_columns< ::Edge, id_pgsql, A >::idEdge_type_
  query_columns< ::Edge, id_pgsql, A >::
  idEdge (A::table_name, "\"idEdge\"", 0);

  template <typename A>
  const typename query_columns< ::Edge, id_pgsql, A >::source_type_
  query_columns< ::Edge, id_pgsql, A >::
  source (A::table_name, "\"source\"", 0);

  template <typename A>
  const typename query_columns< ::Edge, id_pgsql, A >::target_type_
  query_columns< ::Edge, id_pgsql, A >::
  target (A::table_name, "\"target\"", 0);

  template <typename A>
  const typename query_columns< ::Edge, id_pgsql, A >::refGraph_type_
  query_columns< ::Edge, id_pgsql, A >::
  refGraph (A::table_name, "\"refGraph\"", 0);

  template <typename A>
  const typename query_columns< ::Edge, id_pgsql, A >::weight_type_
  query_columns< ::Edge, id_pgsql, A >::
  weight (A::table_name, "\"weight\"", 0);
}

#include "Edge-odb.ixx"

#include <odb/post.hxx>

#endif // EDGE_ODB_HXX
