/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "Edge" CASCADE;

CREATE TABLE "Edge" (
  "idEdge" BIGSERIAL NOT NULL PRIMARY KEY,
  "source" BIGINT NOT NULL,
  "target" BIGINT NOT NULL,
  "refGraph" BIGINT NOT NULL,
  "weight" BIGINT NOT NULL DEFAULT '1');

CREATE INDEX "index_Edge_source"
  ON "Edge" USING BTREE ("source");

CREATE INDEX "index_Edge_target"
  ON "Edge" USING BTREE ("target");

CREATE UNIQUE INDEX "index_Edge_link"
  ON "Edge" USING BTREE (
    "source",
    "target");

CREATE INDEX "index_Edge_refGraph"
  ON "Edge" USING BTREE ("refGraph");

ALTER TABLE "Edge"
  ADD CONSTRAINT "source_fk"
    FOREIGN KEY ("source")
    REFERENCES "Node" ("idNode")
    ON DELETE CASCADE
    INITIALLY DEFERRED,
  ADD CONSTRAINT "target_fk"
    FOREIGN KEY ("target")
    REFERENCES "Node" ("idNode")
    ON DELETE CASCADE
    INITIALLY DEFERRED,
  ADD CONSTRAINT "refGraph_fk"
    FOREIGN KEY ("refGraph")
    REFERENCES "Graph" ("idGraph")
    ON DELETE CASCADE
    INITIALLY DEFERRED;

