/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "inh_poly_contractor" CASCADE;

DROP TABLE IF EXISTS "inh_poly_employee" CASCADE;

DROP TABLE IF EXISTS "inh_poly_person" CASCADE;

CREATE TABLE "inh_poly_person" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "typeid" TEXT NOT NULL,
  "first" TEXT NOT NULL,
  "last" TEXT NOT NULL);

CREATE TABLE "inh_poly_employee" (
  "id" BIGINT NOT NULL PRIMARY KEY,
  "temporary" BOOLEAN NOT NULL,
  CONSTRAINT "id_fk"
    FOREIGN KEY ("id")
    REFERENCES "inh_poly_person" ("id")
    ON DELETE CASCADE);

CREATE TABLE "inh_poly_contractor" (
  "id" BIGINT NOT NULL PRIMARY KEY,
  "email" TEXT NOT NULL,
  CONSTRAINT "id_fk"
    FOREIGN KEY ("id")
    REFERENCES "inh_poly_person" ("id")
    ON DELETE CASCADE);

