/*
 * HnString.cc
 *
 * DO NOT EDIT THIS FILE!
 *
 * This file is automatically generated by obj2ptr.
 * 2002/09/13 12:41:10
 */

#include "HnSRTree/HnString.hh"
#include "HnSRTree/HnStringObj.hh"

/*
 * HnString
 */

const HnString HnString::null;

HnString
new_HnString(void)
{
    HnStringObj *_obj;

    _obj = new HnStringObj();

    if ( _obj->hasConstructorFailed() ) {
        delete _obj;
        return (HnStringObj *)NULL;
    }

    return _obj;
}

HnString
new_HnString(const char *ptr, int n)
{
    HnStringObj *_obj;

    _obj = new HnStringObj(ptr, n);

    if ( _obj->hasConstructorFailed() ) {
        delete _obj;
        return (HnStringObj *)NULL;
    }

    return _obj;
}

HnString
new_HnString(const HnString &string)
{
    HnStringObj *_obj;

    _obj = new HnStringObj(string);

    if ( _obj->hasConstructorFailed() ) {
        delete _obj;
        return (HnStringObj *)NULL;
    }

    return _obj;
}

#define HnClass HnString
#include "HnSRTree/HnClassArray.cpp"

