/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "Graph" CASCADE;

CREATE TABLE "Graph" (
  "idGraph" BIGSERIAL NOT NULL PRIMARY KEY,
  "objectName" VARCHAR(255) NOT NULL,
  "cumulativeMass" INTEGER NOT NULL,
  "DAGCost" DOUBLE PRECISION NOT NULL,
  "MaxTSVDimension" INTEGER NOT NULL,
  "totalTSVSum" DOUBLE PRECISION NOT NULL,
  "shape_xMax" DOUBLE PRECISION NOT NULL,
  "shape_xMin" DOUBLE PRECISION NOT NULL,
  "shape_yMax" DOUBLE PRECISION NOT NULL,
  "shape_yMin" DOUBLE PRECISION NOT NULL,
  "shape_Height" DOUBLE PRECISION NOT NULL,
  "shape_Width" DOUBLE PRECISION NOT NULL,
  "XMLSignature" TEXT NOT NULL,
  "refGraphClass" VARCHAR(255) NOT NULL,
  "refObjectClass" VARCHAR(255) NOT NULL);

CREATE INDEX "index_Graph_graphClass"
  ON "Graph" USING BTREE ("refGraphClass");

CREATE INDEX "index_Graph_objectClass"
  ON "Graph" USING BTREE ("refObjectClass");

CREATE INDEX "index_Graph_objectName"
  ON "Graph" USING BTREE ("objectName");

ALTER TABLE "Graph"
  ADD CONSTRAINT "refGraphClass_fk"
    FOREIGN KEY ("refGraphClass")
    REFERENCES "GraphClass" ("graphClassName")
    ON DELETE CASCADE
    INITIALLY DEFERRED,
  ADD CONSTRAINT "refObjectClass_fk"
    FOREIGN KEY ("refObjectClass")
    REFERENCES "ObjectClass" ("objectClassName")
    ON DELETE CASCADE
    INITIALLY DEFERRED;

