/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "inh_reuse_contractor" CASCADE;

DROP TABLE IF EXISTS "inh_reuse_temporary_employee" CASCADE;

DROP TABLE IF EXISTS "inh_reuse_permanent_employee" CASCADE;

CREATE TABLE "inh_reuse_permanent_employee" (
  "first" TEXT NOT NULL,
  "last" TEXT NOT NULL,
  "id" BIGSERIAL NOT NULL PRIMARY KEY);

CREATE TABLE "inh_reuse_temporary_employee" (
  "first" TEXT NOT NULL,
  "last" TEXT NOT NULL,
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "duration" BIGINT NOT NULL);

CREATE TABLE "inh_reuse_contractor" (
  "first" TEXT NOT NULL,
  "last" TEXT NOT NULL,
  "email" TEXT NOT NULL PRIMARY KEY);

